"""Add patient details including dob, gender, weight, height

Revision ID: 105fda06fce7
Revises: cf3dbe1f66dd
Create Date: 2024-12-05 03:51:06.526248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105fda06fce7'
down_revision = 'cf3dbe1f66dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
