"""Add patient details including dob, gender, weight, height

Revision ID: 83160c368ca5
Revises: 105fda06fce7
Create Date: 2024-12-05 03:57:50.377617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83160c368ca5'
down_revision = '105fda06fce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
